name 'app_static'
maintainer 'Jake Gaylor'
maintainer_email 'jhgaylor@gmail.com'
license 'all_rights'
description 'Installs/Configures a static site behind an nginx server.'
long_description 'Installs/Configures a static site behind an nginx server.'
version '0.1.0'

depends 'base'
depends 'jhg_nginx'
depends 'tar'
depends 'nodejs'